name: Prettier Formatting

on:
  schedule:
    - cron: '0 12 14,28 * *'
  workflow_dispatch: 

permissions: 
  contents: write

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Repo
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Run Prettier
        run: npm run format
      
      - name: Commit formatting changes
        run: |
          git config --global user.name '${{ secrets.GIT_USER_NAME }}'
          git config --global user.email '${{ secrets.GIT_USER_EMAIL }}'
          git add .
          git commit -m "Automation: Formatting code"
          git push